SELECT CUSTOMER_ID 
FROM (
    SELECT 
        CUSTOMER_ID, 
        COUNT(DISTINCT PRODUCT_KEY) AS QUANTITY 
    FROM CUSTOMER
    GROUP BY CUSTOMER_ID) AS sub
WHERE QUANTITY = (SELECT COUNT(DISTINCT PRODUCT_KEY) FROM PRODUCT)