SELECT
    VISITED_ON,
    SUM(AMOUNT) OVER w AS AMOUNT,
    ROUND(AVG(AMOUNT) OVER w, 2) AS AVERAGE_AMOUNT
FROM (
    SELECT 
        VISITED_ON,
        SUM(AMOUNT) AS AMOUNT
    FROM CUSTOMER
    GROUP BY VISITED_ON) AS sub
WINDOW w AS (
    ORDER BY VISITED_ON ASC
    ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)
LIMIT 18446744073709551615 OFFSET 6;