WITH CTE AS (
SELECT 
    MR.USER_ID, 
    U.NAME AS NAME, 
    MR.MOVIE_ID,
    M.TITLE AS MOVIE,
    MR.RATING,
    MR.CREATED_AT
FROM MOVIERATING MR
LEFT JOIN USERS U
    ON MR.USER_ID = U.USER_ID
LEFT JOIN MOVIES M
    ON MR.MOVIE_ID = M.MOVIE_ID
)

(SELECT NAME AS results
FROM CTE
GROUP BY NAME
ORDER BY COUNT(*) DESC, NAME ASC
LIMIT 1)

UNION ALL

(SELECT MOVIE AS results
FROM CTE
WHERE DATE_FORMAT(CREATED_AT, "%m/%Y") = "02/2020"
GROUP BY MOVIE
ORDER BY AVG(RATING) DESC, MOVIE ASC
LIMIT 1)