SELECT DISTINCT 
  STOCK_NAME, 
  SUM(IF(OPERATION='Buy', -PRICE, PRICE)) AS capital_gain_loss
FROM STOCKS
GROUP BY STOCK_NAME

-- OR

SELECT DISTINCT 
  STOCK_NAME, 
  SUM(IF(OPERATION='Buy', -PRICE, PRICE))
    OVER(PARTITION BY STOCK_NAME) AS capital_gain_loss 
FROM STOCKS