SELECT 
    DEPARTMENT,
    EMPLOYEE,
    SALARY
FROM (    
    SELECT 
        D.NAME AS DEPARTMENT,
        E.NAME AS EMPLOYEE,
        SALARY,
        DENSE_RANK() OVER(
            PARTITION BY DEPARTMENTID 
            ORDER BY DEPARTMENTID, SALARY DESC
            ) AS SALARY_RANK
    FROM EMPLOYEE E
    INNER JOIN DEPARTMENT D
        ON E.departmentId = D.id
    ) rank_table
WHERE rank_table.SALARY_RANK = 1

-- OR

SELECT 
    D.NAME AS DEPARTMENT,
    E.NAME AS EMPLOYEE,
    SALARY
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
    ON E.departmentId = D.id
WHERE (DEPARTMENTID, SALARY) IN (
    SELECT
        DEPARTMENTID,         
        MAX(SALARY)
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID 
)