SELECT 
    request_at AS DAY,
    ROUND(
        SUM(IF(STATUS != 'COMPLETED', 1, 0)) / COUNT(STATUS)
        , 2) AS "Cancellation Rate" 
FROM TRIPS
WHERE 
    request_at BETWEEN "2013-10-01" AND "2013-10-03"
    AND CLIENT_ID NOT IN (SELECT USERS_ID FROM USERS WHERE ROLE = 'CLIENT' AND BANNED = 'YES')
    AND DRIVER_ID NOT IN (SELECT USERS_ID FROM USERS WHERE ROLE = 'DRIVER' AND BANNED = 'YES')
GROUP BY request_at 