-- PERFORMS BETTER
SELECT e1.name
FROM Employee e1
JOIN Employee e2 
    ON e1.id = e2.managerId
GROUP BY e1.name
HAVING COUNT(e2.managerId) >= 5;

-- OR

SELECT NAME 
FROM EMPLOYEE
WHERE ID IN (
    SELECT 
      MANAGERID
    FROM EMPLOYEE
    GROUP BY MANAGERID
    HAVING COUNT(MANAGERID) >= 5
    )